### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/fenrir#16]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/fenrir/compare/2fb42cc3d528fea5fe5c801d8dfb4c305037cd96...6175730b8bf4594af8cad5009deaaedccbb09915) was merged to master by grahamjenson.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/fenrir&ref=628ac589a49da02b4cccc7db3d3808b9832fbbb5)

**Comment by frankh** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
frankh | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/fenrir&ref=628ac589a49da02b4cccc7db3d3808b9832fbbb5)
