### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/fenrir#20]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/fenrir/compare/044d26f0fcf4e393133d1e4cbbb02aedcaef40d9...c0e47eec8ad8a97c95c23f5503ee12a10c8f12d7) was merged to master by frankh.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/fenrir&ref=7a845fb596d9aee01be5da6ab6894ecc748f4efa)

**Comment by frankh** [comment]
this was reviewed, somehow got lost

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
grahamjenson | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/fenrir&ref=7a845fb596d9aee01be5da6ab6894ecc748f4efa)
